import = [
    "~/.config/alacritty/catppuccin-latte.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CodeNewRoman Nerd Font", style = "Regular" }
bold = { family = "CodeNewRoman Nerd Font", style = "Bold" }
italic = { family = "CodeNewRoman Nerd Font", style = "Italic" }
size = 16

[keyboard]
bindings = [
    { key = "+", mods = "Command|Shift", action = "IncreaseFontSize" },
    { key = "-", mods = "Command", action = "DecreaseFontSize" },
    { key = "Key6", mods = "Control", chars = "\u001e"}
]

