alias dot="cd $HOME/Projets/dotfiles"
alias ema="emacsclient"
alias keymapp="$HOME/.local/bin/keymapp/keymapp"
alias projects="cd $HOME/Projets"
alias projets="cd $HOME/Projets"
alias notes="cd $HOME/Notes"
